name: Reusable Workflow user

on:
  push:

permissions:
  pull-requests: write

jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  generate-qr-code:
    uses: HoseaCodes/AC-Templates/.github/workflows/expo.yml@main
    with:
      project_id: 29e17e39-0355-454e-978f-d7ee1fd309e3
      expo_slug: exp
    secrets:
      expo_username: ${{ secrets.EXPO_USERNAME }}
      expo_password: ${{ secrets.EXPO_PASSWORD }}

    # secrets:
    #   registry_username: ${{ secrets.REGISTRY_USERNAME }}  # Correct secrets reference
    #   registry_password: ${{ secrets.REGISTRY_PASSWORD }}  # Correct secrets reference
