name: Reusable Workflow user

on:
  push:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  docker:
    uses: HoseaCodes/AC-Templates/.github/workflows/example.yml@main
    with:
      image_name: my-awesome-app
      tag: ${{ github.run_number }}  # Correct GitHub context reference for run number

    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}  # Correct secrets reference
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}  # Correct secrets reference
